### ISSUE TITLE
Not compatible with Authoring Tool?

### ISSUE THREAD

**Issue by christian-wehle** [kunjsharma/adapt-footer#1]
Hi, 
i've just successfully uploaded and enabled this great plugin the Authoring Tool via "Upload Plugin". However, when I want to add it to a project, nothing happens when clicking on the button "Add":
![image](https://user-images.githubusercontent.com/54230380/81821736-82961a00-9532-11ea-9285-5b1a9753fcea.png)

Is there any chance to fix this?

Warm regards,
Chris

**Comment by kunjsharma** [comment]
Hi Chris, my apologies for late response. Component primarily for framework (mentioned in limitations already). You require little modifications in properties.schema to use it with authoring.
